import styled from '@emotion/styled';
import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { Component, lazy, Suspense, useRef } from 'react';
import { Sections } from '../components/Section';
const Hero = dynamic(() => import('../components/hero'), { ssr: false });

const Home: NextPage = () => {
    const iconEl = useRef([]);

    return (
        <>
            <Head>
                <title>KozakBartosz.pl</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Hero iconRef={iconEl} />
            <main>
                {/* <Suspense fallback=""> */}
                {/* </Suspense> */}

                <Sections iconRef={iconEl} />
            </main>

            <footer></footer>
        </>
    );
};

export default Home;
