import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import { Hero } from '../components/hero';
// import { Canvas, useFrame } from '@react-three/fiber';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>KozakBartosz.pl</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Hero />
                <Button>Yolo</Button>
            </main>

            <footer></footer>
        </div>
    );
};

const Button = styled.a`
    display: block;
    border-radius: 3px;
    padding: 1.5rem;
    text-align: center;
    margin: 0.5rem 1rem;
    width: 11rem;
    background: #000;
    color: white;
    border: 2px solid white;
`;

export default Home;
